### ISSUE TITLE
Unexpected token (JSX syntax)

### ISSUE THREAD

**Issue by frg** [kuflash/react-router-sitemap#33]
I tried running the example script and I'm getting this error:
`SyntaxError: C:/.. ../routing.jsx: Unexpected token`

![image](https://cloud.githubusercontent.com/assets/1245426/16363313/e7a66aea-3bc6-11e6-9ace-683c8c02b53c.png)

Running the script using:
`node sitemap-builder.js`

And im requiring 'babel-register' as instructed.

Would appreciate the help!

**Comment by kuflash** [comment]
@frg Hi! What version Node.JS you using? 
Check whether all the necessary dependencies installed: 
`react`
`react-router`,
`babel-preset-es2015`
`babel-preset-react`

**Comment by frg** [comment]
Didn't but after installing I'm getting the same issue.

My package.json looks something like this:
`
...
"dependencies": {
    "react": "^0.13.3",
    "react-router": "^0.13.3",
    "react-router-sitemap": "^1.0.7"
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-react": "^6.5.0",
    "babel-register": "^6.9.0",
    "babel-core": "^5.8.38",
    "babel-loader": "^5.4.0",
    "express": "^4.13.4",
    "http-proxy": "^1.13.2",
    "jsx-loader": "^0.13.2",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  }`

**Comment by kuflash** [comment]
@frg I assume that you are using the old version of the package. You can update them to those used in my package?

**Comment by kuflash** [comment]
@frg problem is resolved?

**Comment by frg** [comment]
Yep, resolved. Even though this is a fast and simple solution I ended up creating a project of my own using PhantomJS to create a comprehensive sitemap. Even though my site defines ~8 routes I've got over 7200 url variations! Anyway, still a great job! Thanks @kuflash :)
