### ISSUE TITLE
TypeError: (0 , _reactRouterSitemap.sitemapBuilder) is not a function

### ISSUE THREAD

**Issue by laurenskling** [kuflash/react-router-sitemap#35]
If I follow this piece of documentation: https://github.com/kuflash/react-router-sitemap/blob/master/api.md#sitemapbuilder

I get an error.

**Comment by kuflash** [comment]
@laurenskling thank you, i will fix it

**Comment by kuflash** [comment]
@laurenskling sorry, I'm slowpoke, but i fixed this error :D Can you try again import sitemapBuilder function?

**Comment by laurenskling** [comment]
Yes it works!!
