### ISSUE TITLE
unexpected character in ... png

### ISSUE THREAD

**Issue by Tbutnyakov** [kuflash/react-router-sitemap#44]
Hello, kuflash! 
Thank you for package!
I wanted to try to use your package, but faced with a strange surprise.

Here is sitemap_builder.

```
require('babel-core/register');
require('babel-polyfill');

const router = require('../src/router').default;
const Sitemap = require('react-router-sitemap').default;

(
  new Sitemap(router).build('http://localhost:3003').save('./sitemap.xml')
);
```

And in console i got:

SyntaxError: c:/someproject/src/assets/img/pages/about.png: Unexpected character '�' (1:0)
[0m[31m[1m>[22m[39m[90m 1 | [39m�PNG
 [90m   | [39m[31m[1m^[22m[39m
 [90m 2 | [39m[37m[41m[1m[22m[49m[39m
 [90m 3 | [39m[37m[41m[1m

Could you suggest what could be the problem?
Thank you!

**Comment by kuflash** [comment]
@Tbutnyakov do you have import png file in your react components? If so, then you should try to add such a construction:

```js
require.extensions['.png'] = function () {
  return null;
};
```

**Comment by Tbutnyakov** [comment]
Yep! It works. I tried to do this  like : 

```
require.extensions['.png', '.jpg', '.somethingelse'] = function () {
  return null;
};

```
And it didn't work. 

In this case:

```
require.extensions['.png'] = function () {
  return null;
};
require.extensions['.jpg'] = function () {
  return null;
};
```

Everything works fine. 
Thank you!:)

**Comment by stefankp** [comment]
@kuflash I get a similar error which isn't solved with the above steps.

Error:
```bash
14:25:49 | web[master !?] $ yarn build:sitemap
yarn run v1.7.0
$ node src/helpers/sitemap.js
[PATH...]/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: [PATH...].png: Unexpected character '�' (1:0)
> 1 | �PNG
    | ^
  2 | 
  3 | 
error Command failed with exit code 1.
```

`sitemap.js`:
```js
require('babel-register');
const Sitemap = require('react-router-sitemap').default;
const Routes = require('../modules/App/routes').default;

require.extensions['.png'] = function () {
  return null;
};

new Sitemap(Routes)
  .build('http://localhost:3001')
  .save('./sitemap.xml');
```

Babel Config:
```json
{
  "ignore": [
    "node_modules/**/*"
  ],
  "presets": [
    "es2015",
    "react"
  ]
}
```

Any idea how to solve this?

**Comment by kuflash** [comment]
@stefankp try moving this is part before require routes:
```js
require.extensions['.png'] = function () {
  return null;
};
```
For example, after `require('babel-register');`

**Comment by stefankp** [comment]
@kuflash that worked 👍 

Next error was, that `babel-preset-react-app` didn't have access to `NODE_ENV`, so added:
```js
process.env.BABEL_ENV = 'development';
process.env.NODE_ENV = 'development';
```

Now it throws a `SyntaxError` because of ES6 `export` syntax in another module, even though the babel preset is configured 🤔 
```bash
22:34:45 | web[master !?] $ yarn build:sitemap
yarn run v1.7.0
$ node src/helpers/sitemap.js
[PATH...]/node_modules/react-apollo/index.js:1
(function (exports, require, module, __filename, __dirname) { export * from './browser';
                                                              ^^^^^^

SyntaxError: Unexpected token export
```

**Comment by kuflash** [comment]
@stefankp it seems to me that this mistake is not entirely relevant to this problem. I will try in the next couple of days to test for this problem. Can you make a test repository where this problem is reproduced? It would be great
