### ISSUE TITLE
How do i use dynamic path created by applyParams in sitemap

### ISSUE THREAD

**Issue by manishachaudhary1234** [kuflash/react-router-sitemap#46]

**Comment by kuflash** [comment]
@manishachaudhary1234 can you describe more?
The example is an [example](https://github.com/kuflash/react-router-sitemap/blob/master/example/sitemap-builder.js#L14-L25) of how to use the dynamic parameters in the routes

**Comment by manishachaudhary1234** [comment]
Solved. Thankyou
