### ISSUE TITLE
Sitemap index: split sitemap for large projects

### ISSUE THREAD

**Issue by Matzu89** [kuflash/react-router-sitemap#49]
Just discovered this, after successfully implementing this library (which is great and works as expected), search engines like `Google` state the following about sitemaps:

`A sitemap file can't contain more than 50,000 URLs and must be no larger than 10 MB uncompressed.`
[(Source)](https://support.google.com/webmasters/answer/183668?hl=en&topic=8476&ctx=topic)

The `sitemap` library used in this project, [supports building](https://www.npmjs.com/package/sitemap#example-of-sitemap-index) a [sitemap index](https://support.google.com/webmasters/answer/75712?visit_id=1-636285817022700702-2934658118&rd=1), which refers to multiple sitemaps, which is acceptable to Google.

I believe this library could be updated to use/support this functionality. 

I suggest the following approach:

- Split sitemap at 49,999 urls -> new sitemap
- Always generate a sitemap index referring to one or multiple sitemaps
- To prevent breaking changes, save splitted sitemaps as chosen filename string-replacing `.xml` with 
`-[:sitemapIndex].xml`.

@kuflash Are you willing to accept a PR implementing this?

**Comment by Matzu89** [comment]
To clarify: I'm working on a project which easily generates 100.000+ urls

**Comment by kuflash** [comment]
@Matzu89 if you can implement this feature, then I will gladly accept PR.

**Comment by Matzu89** [comment]
Great, will push something later this week
