### ISSUE TITLE
How can I get this working with webpack?

### ISSUE THREAD

**Issue by rluncasu** [kuflash/react-router-sitemap#55]
I got this working nicely with my react app.However, since I started using webpack, especially a webpack plugin that does a text replace on placeholders within the app code, the sitemap fails, being unable to parse the code( it's actually invalid due to the placeholders). I need to include this into a webpack plugin so that it uses the webpack processed sources instead of actual ones.Any pointers ? Perhaps someone already did this ?

**Comment by kuflash** [comment]
@rluncasu I didn't create webpack plugin for this. Can you create simple example your case and describe more what you want? I will try implement plugin for webpack.

**Comment by rluncasu** [comment]
@kuflash I've created a repo with a minimal skeleton.
https://github.com/rluncasu/minimal-react-webpack-sitemap

I want react-router-sitemap to work with webpack.DefinePlugin which does a search & replace in /src/common/mutuals/index.js.

Currently react-router-sitemap can't parse the code in that file because it hasn't been transformed by webpack.

It does look like what is needed is building a react-router-sitemap webpack plugin.

**Comment by kuflash** [comment]
@rluncasu if I right understood you, you want use some variables defined in DefinePlugin for generate routes for react application (for exmaple), and use generated routes for sitemap builder?

**Comment by rluncasu** [comment]
@kuflash I'm not using the variables for generating routes but in the routes controller. Anyway, the file is referenced and because it's not valid code (not until webpack DefinePlugin replaces the placeholders) sitemap builder errors out when trying to load the routes.

**Comment by kuflash** [comment]
@rluncasu ok, I'm understood. Can you try use this [plugin](https://www.npmjs.com/package/react-router-path-extractor-webpack-plugin)? It's have callback with array of paths. You can try use API [method](https://github.com/kuflash/react-router-sitemap/blob/master/api.md#sitemapbuilder)  from my modules for generate sitemap from webpack. Report the result, please.

**Comment by rluncasu** [comment]
@kuflash , I've tried the plugin you suggested but unfortunately that plugin produces the same error (the plugin itself, not react-router-sitemap).
Looking at his code, I can see the reason, instead of using the compiled sources, it loads the routes directly from file.
Webpack plugins must use of the 'compilation' object in order to access the compiled sources (react-router-path-extractor-webpack-plugin doesn't do that).

**Comment by kuflash** [comment]
@rluncasu ok, I'm not sure that this is possible. But I will research this is question. If you can find something on this topic, then please let me know.

**Comment by rluncasu** [comment]
I figured out a solution.Posting it here so it may help others:

The base issue was that the js code wasn't valid code until it ran through webpack's DefinePlugin.
To solve this, I changed the name of the placeholders inside DefinePlugin config:
*from:*
```js
        new webpack.DefinePlugin({
            DEVELOPMENT: "true",
            PRODUCTION: "false",
            NODE_ENV: JSON.stringify('testingshits'),
        })
```
*to:*
```js
        new webpack.DefinePlugin({
            "process.env.DEVELOPMENT": "true",
            "process.env.PRODUCTION": "false",
            "process.env.NODE_ENV": JSON.stringify('testingshits'),
        })
```
**and in my code**
*from:*
```js
export const isDevelopment = DEVELOPMENT ;
```
*to:*
```js
export const isDevelopment = process.env.DEVELOPMENT || false;
```

This way, when webpack runs the code through DefinePlugin it will replace the entire string "process.env.DEVELOPMENT" and when running the sitemap builder through nodejs the code will still be valid because process.env.DEVELOPMENT is valid code(process.env is defined).

thanks a lot @kuflash for working through this with me !

**Comment by kuflash** [comment]
@rluncasu cool! Thank you!
