### ISSUE TITLE
Cannot read property 'limitCountPaths' of undefined

### ISSUE THREAD

**Issue by aj-anuragjain** [kuflash/react-router-sitemap#56]
Upgrade to v1.1.0 from 1.0.8 throw the error.

**Comment by aYo-dev** [comment]
This is happening because in build method you don't have second parameter (it have to be empty object or object with key 'limitCountPaths').

**Comment by kuflash** [comment]
@aj-anuragjain sorry, I'm will check this case

**Comment by kuflash** [comment]
@aj-anuragjain I fixed this error. Thank you for this report!
