### ISSUE TITLE
Unexpected character for PNG

### ISSUE THREAD

**Issue by GarrettJMU** [kuflash/react-router-sitemap#80]
Read through the previous issues and wasn't able to solve the issue.

Versions:
React: 16.5
react-router-sitemap: 1.1.5
react-router: 4.3.1

.babelrc:
`{
  "presets": [
    "env",
    "react",
    "stage-3"
  ],
  "plugins": [
    "transform-decorators-legacy",
    "transform-inline-environment-variables",
    "recharts"
  ]
}`

Sitemap.js

`require('babel-register')

require.extensions[
  ('.svg', '.png', '.jpeg', '.jpg', 'css', 'scss', '.ico')
  ] = function() {
  return null;
};

const routes = require('./SitemapRoutes').default
const Sitemap = require('react-router-sitemap').default;

new Sitemap(routes).build("http://localhost:4000").save("./sitemap.xml");`

**Comment by xEcEz** [comment]
It seems that including several extensions at once in require.extensions does not work. I've got it working by including them one by one, like this:

```
require.extensions['.css'] = function () {
  return null;
};
require.extensions['.png'] = function () {
  return null;
};
require.extensions['.svg'] = function () {
  return null;
};
require.extensions['.jpg'] = function () {
  return null;
};
```
