### ISSUE TITLE
Syntax Error: Unexpected token import

### ISSUE THREAD

**Issue by adityatandon007** [kuflash/react-router-sitemap#90]
Running `node sitemap-generator.js` in my react project that builds using webpack gives this error:

/home/batman/webUI/src/components/index.js:77 return import('./shopping/shoppingByBrand/shoppingByBrand');
               ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at loader (/home/batman/webUI/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/batman/webUI/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18) 

My project uses `react-router-dom v4.2.2`
Here is how the **sitemap-generator.js** looks:

require("babel-register")({
    presets: ["es2015", "react"]
});

const router = require("./src/sitemap-routes").default;
const Sitemap = require("react-router-sitemap").default;

function generateSitemap() {
    return new Sitemap(router)
        .build("http://localhost:80")
        .save("./public/sitemap.xml");
}

generateSitemap();

Here is how the `.babel.rc` looks:
{
  "presets": [
    "es2015",
    "react",
    "stage-0"
  ],
  "env": {
    "production": {
      "plugins": [
          "transform-react-remove-prop-types",
          "transform-react-constant-elements",
          "transform-react-inline-elements",
          "transform-react-pure-class-to-function"
      ]
    }
  }
}

I have added all the required dev dependencies as mentioned i.e.
   `"babel-cli": "6.14.0",
    "babel-core": "6.14.0",
    "babel-eslint": "6.1.2",
    "babel-loader": "7.1.2",
    "babel-plugin-transform-decorators-legacy": "1.3.4",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-inline-elements": "6.22.0",
    "babel-plugin-transform-react-remove-prop-types": "0.2.9",
    "babel-plugin-transform-runtime": "6.15.0",
    "babel-polyfill": "6.26.0",
    "babel-preset-env": "1.6.0",
    "babel-preset-es2015": "6.14.0",
    "babel-preset-react": "6.11.1",
    "babel-preset-stage-0": "6.5.0",
    "babel-preset-stage-2": "6.24.1",
    "babel-register": "6.26.0",
    "clean-webpack-plugin": "0.1.17",`

@kuflash  please help

**Comment by kuflash** [comment]
@adityatandon007 can you create repository with project where problem is reproduce? I'm try reproduce your configuration in my project and it's all ok, sitemap is built

**Comment by adityatandon007** [comment]
@kuflash my project doesn't use `react-router` it uses `react-router-dom` and I have an entirely different custom setup for loading my routes. I cannot understand why running the `node sitemap-generator.js` is trying to run my `src/components/index.js` which has import statements for loading components specific to a route. So `src/components/index.js` looks like this: 

import React from 'react';
import Loadable from 'react-loadable';

export const ShoppingByBrand = Loadable({
    loader: () => import('./shopping/shoppingByBrand/shoppingByBrand'),
    loading () {
        return <div>Loading...</div>;
    }
});


export const BrandProfileWrapper = Loadable({
    loader: () => import('./profile/brand/BrandProfileWrapper'),
    loading () {
        return <div>Loading...</div>;
    }
});




export const StoreProfileWrapper = Loadable({
    loader: () => import('./profile/store/StoreProfileWrapper'),
    loading () {
        return <div>Loading...</div>;
    }
});
 
So, I replaced all the `import` with `require` because I thought it might be because node doesn't have the support for import or either I would have to run it with babel, so I replaced all the `import` statements with `require` and the error did resolve, but now it is showing different error regarding scss files for my project like this:

/home/batman/webUI/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /home/batman/webUI/src/components/feed/feed.scss: Unexpected token (1:0)
> 1 | .feed{
    | ^
  2 |   width: 100%;
  3 |   .mobile-view {
  4 |       display: none;
at Parser.pp$5.raise (/home/batman/webUI/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/batman/webUI/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/batman/webUI/node_modules/babylon/lib/index.js:3750:12)
    at Parser.parseExprAtom (/home/batman/webUI/node_modules/babylon/lib/index.js:7238:22)
    at Parser.pp$3.parseExprSubscripts (/home/batman/webUI/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/batman/webUI/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/batman/webUI/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/batman/webUI/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/batman/webUI/node_modules/babylon/lib/index.js:3344:19)
    at Parser.parseMaybeAssign (/home/batman/webUI/node_modules/babylon/lib/index.js:6474:20)

Can you help with this.

**Comment by adityatandon007** [comment]
@kuflash one more thing why it is trying to read those `scss` files. I think building sitemap has nothing to do with those styles. Also why it is trying to read that `src/components/index.js ` file, when all my route related info is in `routes.js`

**Comment by kuflash** [comment]
@adityatandon007 maybe you are importing a `scss` file somewhere, which is chained into a file `routes.js`. For resolve this is problem you can try this is solution: https://github.com/kuflash/react-router-sitemap/issues/44

**Comment by adityatandon007** [comment]
@kuflash I followed the instructions mentioned in #44 and ignored all my styles files and images using the solution. But now it is throwing  this error:

SyntaxError: /home/batman/webUI/src/components/feed/PostedBy/PostedBy.js: Missing class properties transform.
  308 |     }
  309 | 
> 310 |     show = (e) => {
      |     ^
  311 |         popoverStore.register(this.hide);
  312 |         this.setState({ isPopoverShown: true });
  313 |     };

**Comment by kuflash** [comment]
@adityatandon007 it problem of babel: https://github.com/babel/babel/issues/2729

**Comment by adityatandon007** [comment]
@kuflash yes I figured that out, basically my order for presets for wrong in `.babelrc` but still I couldn't generate the sitemap. It was showing an error related to `window.eventEmitter` undefined. How could I resolve that, plus it would be nice of you to post an example on how to integrate this with webpack.

**Comment by adityatandon007** [comment]
@kuflash I did generated the sitemap but after creating a new `sitemap-routes.js` specially to feed into `sitemap-generator.js` because my original `routes.js` is configured differently and it loads different components related to the path it matches and a lot custom redirection is also there, so I created a new routes for sitemap that looks similar to what is mentioned in example: 

import React from 'react';
import { Switch, Route } from 'react-router-dom';

`export default (
    <Switch>
	<Route path='/'/>
        <Route path='/feed'/>
        <Route path='/login'/>
        <Route path='/my-network'/>
        <Route path='/settings/edit'/>
        <Route path='/shopping/:gender'/>
        <Route path='/shopping/:gender/:category'/>
        <Route path='/shopping/:brand/:gender/:category'/>
        <Route path='/trending'/>
        <Route path='/brand/:username'/>
        <Route path='/store/:id'/>
        <Route path='/:username'/>
	</Switch>
);`

and then updated my `sitemap-generator.js` like this:

const router = require("./src/sitemap-routes").default;
const Sitemap = require("react-router-sitemap").default;
const axios = require("axios");
axios.get('http:/example.com/usernames')
  .then((response) => {
      console.log("response",response.data);
    const paramsConfig = {
	'/:username': [
	  { username: response.data.usernames }, // array of ids
	]
    };
    new Sitemap(router)
    .applyParams(paramsConfig)
      .build('http://localhost:80')
      .save("./sitemap.xml")
  }) .catch(error => {
    console.log("error",error)
  })

and it generated a `sitemap.xml` . I know I had to similarly map my rules for my other dynamic paths, but that is not a problem, Although I need to add `changefreq` and `priority` tag but I know this library doesn't have the support for it  but still it great.
Now only one thing is left, how can I automate this thing whenever my project is deployed and sometimes the dynamic data that I am fetching using get api is large and it takes a lot of time to get the response. So now suppose a situation where 2 new username are added but I have 100,000 users already  so why to make a call to fetch again those 100,000 users for getting only 2 new users. Can anything be done regarding that ? 

PS: Thanks a lot for this awesome library, I will try to contribute to this repository in case I find some time :+1: :slightly_smiling_face:

**Comment by kuflash** [comment]
@adityatandon007 I not sure how implement your requested feature. In core my library I use libara [sitemap.js](https://github.com/ekalinin/sitemap.js) and I don't found how concatenating several xml files. I will be very grateful if you try to conduct a research and send PR.

**Comment by adityatandon007** [comment]
@kuflash  thanks for the help but it would be nice of you if you could add that snippet for removing styles and images in doc as optional, or if you want I could send a PR for that.
